[package]
name = "vocoder_volcano"
version = "0.1.0"
edition = "2021"

[lib]
name = "vocoder_volcano"
crate-type = ["cdylib", "rlib"]

[dependencies]
vulkano = "0.32"
vulkano-shaders = "0.32"
vulkano-util = "0.32"
bytemuck = "1.8.0"
lv2 = "0.6.0"

[dev-dependencies]
rodio = "0.16"
hound = "3.5"
